### ISSUE TITLE
我自定义了个键盘，支持输入小数点的。如何根据输入框的内容进行加减

### ISSUE THREAD

**Issue by yushan023** [jkpang/PPNumberButton#4]
如果数量为整数以1为单位加减，如果数量有小数以0.1为单位加减

**Comment by jkpang** [comment]
你把PPNumberButton中有整数加减的地方修改成浮点型加减就可以了, 例如 : NSInteger number = _textField.text.integerValue + 1; ---> CGFloat number = _textField.text.floatValue + 1.f;  @yushan023

**Comment by yushan023** [comment]
好的  谢谢
